= Slides

== Miembros del grupo 

* Guiu Puigantell 
* Diego Yesid Amador
* Andres Rojas

== Links a elementos externos del proyecto

Trello: https://trello.com/b/kZctgkZO/grupo6rojaspuigantellamador +
Figma: https://www.figma.com/team_invite/redeem/44RI6co5hDKzbLXxDJyQHi +
Git: https://git.copernic.cat/gpuigantell/grupo6rojaspuigantellamador

== Isardvdi

Fer servir la maquina del Guiu Puigantell. IP: 192.168.50.166

== Preparació del servidor en Isardvdi

=== Intalació mysql

sudo apt install default-mysql-server

=== Instalació Git
sudo apt install git

=== Mostrar errors en php

Entrem a la ruta /etc/php/8.2/apache2 i modifiquem les següents dos línies:

display_errors = On

error_reporting = E_ALL


=== Configuració del projecte
Per poder fer servir el projecte en la màquina virtual hem de seguir els següents pasos:

-> sudo ip addr add 192.168.50.166/24 dev enp3s0

-> sudo ip link set enps30 up

-> Només hem de canviar en el fitxer /var/www/html/config/config.php i canviar la ip de la base de dades a la 127.0.0.1 per a ser el localhost.
