$install_requirements = <<SCRIPT
echo ">>> Installing Base Requirements"

  # contraseña del root
    passRoot=1234

  # usuario, contraseña y nombre de la base de datos
    usuario="usuario"
    contrasena="usuario"
    nombreBD=dbGrupo6

  # update de la maquina
    sudo apt update
    sudo apt install -y vim curl build-essential python3-software-properties git

  # establecer contraseña al root de mysql
    sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password $passRoot"
    sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $passRoot"

  # instalar MySQL
    sudo apt -y install mysql-server

  # creacion de la base de datos
    sudo mysql -uroot -p$passRoot -e "CREATE DATABASE $nombreBD"

  # creacion de usuario con permisos
    sudo mysql -uroot -p$passRoot -e "CREATE user '$usuario'@'%' IDENTIFIED BY '$contrasena';"
    sudo mysql -uroot -p$passRoot -e "GRANT ALL PRIVILEGES ON *.* TO '$usuario'@'%';"

  # Dar permisos de conexion remota al mysql
    sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
    sudo systemctl restart mysql

  # creacion de las tablas
    sudo mysql -uroot -p$passRoot $nombreBD <<EOF
	
      CREATE TABLE estilos(id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(255), css_resource VARCHAR(255), img_resource VARCHAR(255));

      CREATE TABLE presentaciones(id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(255), descripcion VARCHAR(255), estilo_id INT, pin VARCHAR(50), FOREIGN KEY (estilo_id) REFERENCES estilos(id), vista_cliente TINYINT(1) DEFAULT 0, nombreURL VARCHAR(255));

      CREATE TABLE diapositivas(id INT PRIMARY KEY AUTO_INCREMENT, nDiapositiva INT, titulo VARCHAR(255), contenido VARCHAR(255), tipoDiapositiva VARCHAR(255), imagen VARCHAR(255), pregunta VARCHAR(255), presentaciones_id INT, FOREIGN KEY (presentaciones_id) REFERENCES presentaciones(id) on delete cascade);

      CREATE TABLE respuestas(id INT PRIMARY KEY AUTO_INCREMENT, respuesta VARCHAR(255), id_diapositiva INT, FOREIGN KEY (id_diapositiva) REFERENCES diapositivas(id) on delete cascade);

      insert into estilos(nombre, css_resource, img_resource) values("estilo1", "estilo1.css", "estilo1.PNG");
      insert into estilos(nombre, css_resource, img_resource) values("estilo2", "estilo2.css", "estilo2.PNG");
      
EOF
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/mantic64"

  config.vm.define "db" do |db|
      db.vm.network "private_network", ip: "172.17.1.20"
      db.vm.network "forwarded_port", guest: 3306, host: 8306
      db.vm.network "forwarded_port", guest: 80, host: 8080
      db.vm.provision "shell", inline: $install_requirements
  end
end
