$install_requirements = <<SCRIPT
echo ">>> Installing Base Requirements"

#!/usr/bin/env bash

DBHOST=localhost
DBNAME=dbGrupo6
ROOTPASSWD=1234

# Usuario y contraseña
USER="usuario"
PASS="usuario"

sudo apt update
sudo apt install -y vim curl build-essential python3-software-properties git

sudo debconf-set-selections <<< "mysql-server mysql-server/root_password password $ROOTPASSWD"
sudo debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $ROOTPASSWD"

# Instalar MySQL
sudo apt -y install mysql-server

sudo mysql -uroot -p$ROOTPASSWD -e "CREATE DATABASE $DBNAME"

# Crear un usuario y otorgar permisos
sudo mysql -uroot -p$ROOTPASSWD -e "CREATE USER '$USER'@'%' IDENTIFIED BY '$PASS';"
sudo mysql -uroot -p$ROOTPASSWD -e "GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%';"

# Actualizar el archivo de configuración de MySQL para permitir acceso remoto a la base de datos
sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf

sudo systemctl restart mysql

# Crear tablas en la base de datos
sudo mysql -uroot -p$ROOTPASSWD $DBNAME <<EOF

CREATE TABLE presentaciones(id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(255), descripcion VARCHAR(255));

CREATE TABLE diapositivas ( id INT PRIMARY KEY AUTO_INCREMENT, nDiapositiva INT, titulo VARCHAR(255), contenido VARCHAR(255), tipoDiapositiva BOOLEAN, presentaciones_id INT, FOREIGN KEY (presentaciones_id) REFERENCES presentaciones(id));

EOF
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/mantic64"

  config.vm.define "db" do |db|
      db.vm.network "private_network", ip: "172.17.1.20"
      db.vm.network "forwarded_port", guest: 3306, host: 8306
      db.vm.network "forwarded_port", guest: 80, host: 8080
      db.vm.provision "shell", inline: $install_requirements
  end
end
